export const LOGIN_TASK = "LOGIN_TASK";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const AUTHENTICATION = 'AUTHENTICATION';
export const HOME_SEARCH_WORKER = 'HOME_SEARCH_WORKER';
export const HOME_SEARCH_SUCCESS = 'HOME_SEARCH_SUCCESS';
export const HOME_LIST_CATEGORY = 'HOME_LIST_CATEGORY';
export const HOME_LIST_SUCCESS = 'HOME_LIST_SUCCESS';